language: java
jdk:
  - openjdk8

env:
  global:
  - secure: 6QkmEjgKfD5HPckQ3YCcc0/qC56Pc1QKFO15s2oIQQUZNljiLBzbaXKUIlS7+M0WCJuw7enWgqDQCpf4BIXWIJbSj1oa6stamfzD1DRUlC1CjSZ/r04lsqvk1wxVxe5zRSCrH8lgmgLskZtWTxR82A/4aC/6Cu4JHNTAUcZLT/yX+z3cjG4uKt7cB7A0ORSsbT3Q1lV11+dLdB7WtBCmA4jWtPhLoT9U/YAKg3c98hB5pH5yEQk+xHdZSkKGcNbJGhWCTNQkLm+5GGjpnZAb59FeHrO6uOvxp1pNYi8MCTOhpSkqUwT3D5xbYricbipgxlgI88uW7LbFYwJow4bKbqvtNKLY7kWWjdlSk5LAJM2tDcOCbVcEVbWPQWNVRXS4TlJI1pZSLa4EpsTCSV+aSQ0pmz7GnexAlBVtZqxd+WBXhHSs8r6hiNoPISSAWH8cuz9pQuEU7c9/H19mFDBeJNXbC74CHCpsR+ixEDridcEu7+HalL0ZjbtIVMHpOc77eCANFmXsmUgwKMmb/bwBLwwCGCF7rMv7fNAaT8fcr6czdgxEHH3psmN1poAfO1A+7KG4wsQJy7auOOs+6ckWEJgnhKXQH2LOYpe+QixY5FCfFAXj2fXt8NF0sO4WIZnRC9Z9MKG/bVpSgT4sdYhLvmC92g9trewnk8yIvprjtLw=
  - secure: rGzR3m91JHyD1EXSZRVYNQzSsfMl2c/tNaS6uqdHsgJh9a5RMy0aeBlcqVv+txRHURmjh2RtU92ZKDuk3NO2UxWJvw7FcNslqhWhaeAC+mbuoQABzhTC8sFTlEx5pDhVVL5ZNbjpvWGpQv49uyO1NPBgTbn7JtNK2YpYAc4JiP6OJRjKe2BYIYR1LenHv3eO96NUei8nkRnyr/AzR1+8S60HLhoDkO73K0qsNNN+Tz6ESDRnVzcJe6cB3wjO1vrvx6/hFeGowol7BeF62zPZe9BJBqmedTlcxFEb5P4Z6X5Fus0lEPK3s4k/FCByT0KZNU4XTdPo67m0TWu9w2uJyN+chWq9U2ClEVqc7/BSgmh2WTcZZe7rMF/f8AHUc8hnktYmSDKmjawwI72M+gib8SH0XQogtPlWuEajBHyHPJKvbPKG73t5DEFKCuBCTA8TAC1L2DfmGEFGG98oYwvEVH8yvfkHNbVToO+MdyjgiVN3qtKnYai4GCK0zxVmzsqGwnz0o2LK5qM1FwkcbrSgz8ucmmcrSP0CGkqbtAjZKlneE2HYRbLoYYdKn6qUTXVAIPOY9NrLSleH10TNLIh93aNTj1EaYHvAZ6Jzr4dekh4G+xMeREbZrYFnkUhHKfB2DmS+UjiVR2Jz9HJBnZoVRia5V7b3n8zJekeD4CVlIVA=

script:
  - mvn install

after_success:
  - curl -T service/target/service.war -u $FTP_USER:$FTP_PASSWORD ftp://waws-prod-dm1-055.ftp.azurewebsites.windows.net/site/wwwroot/webapps/
